push_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  virtual_joint1_controller1:
    type: effort_controllers/JointPositionController
    joint: virtual_joint1
    pid: {p: 10.0, i: 0.01, d: 10.0}
